version: "3"
services:
  api:
    build: .
    image: tttapi
    ports:
      - "8080:8080"
    volumes:
      - ./cont_logs:/app/logs
  ui:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    depends_on:
      - api